import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Player from "./components/player";
import { useState } from "react";
import { HlsConfig } from "hls.js";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [cameraId, setCameraId] = useState<string>("3SD343939D4V");
  const [startTime, setStartTime] = useState<Date>(new Date("2024-08-17T18:52:00Z"));
  const [endTime, setEndTime] = useState<Date>(new Date("2024-08-17T18:53:00Z"));

  const [jwt, setJwt] = useState<string>("");
  const [baseUri, setBaseUri] = useState<string>("https://streams.ui.dev.conxai.ai");

  const [playlistUri, setPlaylistUri] = useState<string>("");
  
  const [hlsConfig, setHlsConfig] = useState<Partial<HlsConfig>>({})
  return (
    <>
      <Head>
        <title>Hls Canvas Player</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <form action="">
          <input
            type="text"
            placeholder="JWT"
            value={jwt}
            onChange={(e) => setJwt(e.target.value)}
          />
          <input
            type="text"
            placeholder="BaseUri"
            value={baseUri}
            onChange={(e) => setBaseUri(e.target.value)}
          />
          <input
            type="text"
            placeholder="Camera ID"
            value={cameraId}
            onChange={(e) => setCameraId(e.target.value)}
          />
          <input
            type="datetime-local"
            value={startTime.toISOString().slice(0, 16)}
            onChange={(e) => setStartTime(new Date(e.target.value))}
          />
          <input
            type="datetime-local"
            value={endTime.toISOString().slice(0, 16)}
            onChange={(e) => setEndTime(new Date(e.target.value))}
          />

          <button
            disabled={!baseUri || !cameraId || !startTime || !endTime}
            onClick={(e) => {
              e.preventDefault();

              if (jwt)
                setHlsConfig({
                  xhrSetup: (xhr, url) => {
                    if (!url.startsWith(baseUri)) return;

                    xhr.setRequestHeader("Authorization", `Bearer ${jwt}`);
                  },
                });
                const newUri = `${baseUri}/playlist.m3u8?cameraId=${cameraId}&start=${startTime.toISOString()}&end=${endTime.toISOString()}`

                if (playlistUri === newUri) {
                  setPlaylistUri("");
                }


              setPlaylistUri(newUri);

            }}
          >
            Load
          </button>
        </form>
        {playlistUri && <Player playlist={playlistUri} hlsConfig={hlsConfig}/>} 
      </main>
    </>
  );
}
